### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [JacobPorter/InfoTrim#1]
Hi,

you don't mention if this is Python 2.7 or 3? I have tried both.. Python 3 gives the error below:

Thanks,

Theo

Traceback (most recent call last):
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 5, in <module>
    from Utilities import SeqIterator
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/Utilities/SeqIterator.py", line 2, in <module>
    import Constants
ModuleNotFoundError: No module named 'Constants'

**Comment by theo-allnutt-bioinformatics** [comment]
I tried 'pip install Constants' but still get the error.

**Comment by theo-allnutt-bioinformatics** [comment]
I am using conda.. I copied the Constants.py file from Utilities to site-packages for the environment and got the error below.

Starting InfoTrim 0.1.0 by Jacob Porter.
Using file 'fasta/102.fasta'. Please wait.
Current time: 2020-02-19 15:09:34.761069
Writing output to file 'infotrim/102.fasta'.
Using the following arguments.
r=0.4 s=0.1 m=25.0 t=None processes=12 ascii_offset=33, balanced=False linear=True entropyOnly=False verbose=False
Process Process-2:
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
Process Process-3:
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-5:
Process Process-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-7:
Traceback (most recent call last):
Process Process-6:
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-10:
Traceback (most recent call last):
Process Process-8:
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
Process Process-9:
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
Process Process-11:
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
Process Process-12:
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
Process Process-13:
Traceback (most recent call last):
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    self.run()
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
IndexError: string index out of range
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    self.run()
    self.run()
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    self.run()
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    self.run()
  File "/home/allnutt.t/.conda/envs/py2/lib/python2.7/multiprocessing/process.py", line 114, in run
    balanced=balanced, entropyOnly=entropyOnly)
    self._target(*self._args, **self._kwargs)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 174, in trim_reads_multi
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
IndexError: string index out of range
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
    balanced=balanced, entropyOnly=entropyOnly)
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
IndexError: string index out of range
    balanced=balanced, entropyOnly=entropyOnly)
    balanced=balanced, entropyOnly=entropyOnly)
    trimmed_read = trim_read(read, alpha, beta, gamma, m, t, offset, balanced, linear, entropyOnly, verbose)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 126, in trim_read
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
    balanced=balanced, entropyOnly=entropyOnly)
  File "/stornext/HPCScratch/home/allnutt.t/scripts/InfoTrim/InfoTrim.py", line 57, in calculate_read_trim_position_linear
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range
IndexError: string index out of range
IndexError: string index out of range
    prob_correct = 1 - 10**((ord(phred[i])-offset)/(-10.0))
IndexError: string index out of range

**Comment by JacobPorter** [comment]
I have gotten it to work in Python 3.7.3, but I think it was tested against
Python 2.7.  Constants.py is a file that should be in the Utilities
folder, although if it can't be found by the Python interpreter, it may not work.  It is used by the SeqIterator.py file found in the same folder.

InfoTrim doesn't use pip or conda installation since InfoTrim is pure
Python.

It appears that you are using a fasta file, but InfoTrim only supports fastq files.  Using a fasta file should cause the error that you are seeing.

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks, stupid of me! I only wanted to use the entropy filter so I used my prefiltered fastas.

**Comment by JacobPorter** [comment]
InfoTrim now works on fasta files (the phred base calling term gets effectively turned off), and I confirmed that it works on both Python 2.7 and Python 3.7.  It now has a linear-time trimmer that trims from the beginning and the end (instead of just the end).
